#config_version=6

mode:
  priority: 1500

mode_settings:
  display_delay_ms: 2000
  # keep_multiplier: true
  bonus_entries:
    - entry: ramps_combo
      text: "Ramps Combo"
      player_score_entry: ramps_combo_count
      score: 10_000
      reset_player_score_entry: true
    - entry: saints_confronted
      text: "saints confronted"
      player_score_entry: saints_confronted_ball_count
      score: 20_000
      skip_if_zero: false
      reset_player_score_entry: true
    - entry: saints_defeated
      # You should use a slide_player: in your bonus mode with slide entries based on these names, so when the bonus mode posts that entry, you can show a slide with the relevant information for that bonus entry
      text: "saints defeated"
      player_score_entry: saints_defeated_count
      score: 20_000
      skip_if_zero: true
      reset_player_score_entry: true


slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial # display some initial text before the entry calculations are shown
  bonus_entry:
    bonus:
      action: update

sound_player:
  mode_bonus_started:
    Dramatic-02-sanctuary-precept-of-death-mp3cut:
      bus: effects
      volume: 0.5
