#config_version=6

ball_devices:

  bd_plunger:
    ball_switches: s_outlane_left
    mechanical_eject: true

  bd_trough:
    ball_switches: s_outlane_right
    mechanical_eject: true
    eject_targets: bd_plunger
    tags: trough, home, drain
