#config_version=6

ball_devices:

  bd_plunger:
    ball_switches: s_outlane_left
    mechanical_eject: true

  bd_trough:
    ball_switches: s_outlane_right
    mechanical_eject: True
    tags: trough, home, drain
