#config_version=6

ball_devices:

  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    mechanical_eject: true
    player_controlled_eject_event: auto_launch_plunger
    eject_timeouts: 3s

  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3, s_trough_4, s_trough_5
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain

  bd_kickout:
    ball_switches: s_kickout
    eject_coil: c_kickout
    eject_timeouts: 2s

  bd_scoop:
    ball_switches: s_scoop_1, s_scoop_2, s_scoop_3, s_scoop_jam
    eject_coil: c_scoop
    eject_timeouts: 2s
