#config_version=6

mode:
  start_events: start_mode_hurryup
  stop_events: stop_mode_hurryup
  priority: 1000

event_player:
  hurryup_hit: stop_mode_hurryup
  timer_hurryup_timer_tick{ticks<=3}:
    hurryup_value:
      current_hurryup:
        type: int
        value: 100_000
  timer_hurryup_timer_tick{ticks>3}:
    hurryup_value:
      current_hurryup:
        type: int
        value: 100_000 - ticks * 2_000
  timer_hurryup_timer_complete: stop_mode_hurryup

shots:
  hurryup:
    switch: s_kickout

slide_player:
  mode_hurryup_started: hurryup

timers:
  hurryup_timer:
    end_value: 28
    tick_interval: 200ms
    start_running: true

variable_player:
  hurryup_hit:
    score: 100_000 - device.timers.hurryup_timer.ticks * 2_000
